CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     varchar(255) not null,
    email    varchar(255) not null UNIQUE,
    login    varchar(255) not null UNIQUE,
    birthday date         not null
);


CREATE TABLE IF NOT EXISTS friends
(
    user_id   BIGINT REFERENCES users (id) ON DELETE CASCADE,
    friend_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT friends_key PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS mpa
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255) not null unique,
    description varchar(255)
);


CREATE TABLE IF NOT EXISTS film
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255) not null,
    description varchar(100) not null,
    release_date date         not null,
    duration    INTEGER      not null,
    mpa_id      INTEGER REFERENCES mpa (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS likes
(
    film_id BIGINT REFERENCES film (id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT likes_key PRIMARY KEY (film_id, user_id)

);

CREATE TABLE IF NOT EXISTS genre
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE

);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id  BIGINT REFERENCES film (id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genre (id) ON DELETE CASCADE,
    CONSTRAINT film_genre_key PRIMARY KEY (film_id, genre_id)
);
