DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR NOT NULL,
    email    VARCHAR NOT NULL UNIQUE,
    login    VARCHAR NOT NULL UNIQUE,
    birthday DATE    NOT NULL
);

CREATE TABLE IF NOT EXISTS genre
(
    id   INT PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa
(
    id   INT PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS director
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS friends
(
    user_id   BIGINT    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    friend_id BIGINT    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    date      TIMESTAMP ,
    CONSTRAINT friends_pk PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS film
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR NOT NULL,
    release_date DATE    NOT NULL,
    description  VARCHAR NOT NULL,
    duration     INT     NOT NULL,
    mpa_id       INT     NOT NULL REFERENCES mpa (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS likes
(
    user_id BIGINT    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    film_id BIGINT    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    date    TIMESTAMP ,
    CONSTRAINT likes_pk PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS film_director
(
    film_id     BIGINT NOT NULL REFERENCES film (id) ON DELETE CASCADE,
    director_id BIGINT NOT NULL REFERENCES director (id) ON DELETE CASCADE,
    CONSTRAINT film_director_pk PRIMARY KEY (film_id, director_id)
);

CREATE TABLE IF NOT EXISTS film_genre
(
    genre_id INT    NOT NULL REFERENCES genre (id) ON DELETE CASCADE,
    film_id  BIGINT NOT NULL REFERENCES film (id) ON DELETE CASCADE,
    CONSTRAINT film_genre_pk PRIMARY KEY (genre_id, film_id)
);

CREATE TABLE IF NOT EXISTS review
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content     VARCHAR   ,
    date        TIMESTAMP ,
    is_positive boolean  ,
    useful      bigint      ,
    user_id     BIGINT    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    film_id     BIGINT    NOT NULL REFERENCES film (id) ON DELETE CASCADE,
    UNIQUE (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS event_type
(
    id   INT PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE IF NOT EXISTS operation_type
(
    id   INT PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE IF NOT EXISTS REVIEW_RATING
(
    id bigint REFERENCES REVIEW (id) ON DELETE CASCADE,
    user_id bigint REFERENCES USERS (id) ON DELETE CASCADE,
    liked boolean,
    PRIMARY KEY (id, user_id, liked)
);

CREATE TABLE IF NOT EXISTS events
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TIMESTAMP  bigint,
    user_id    BIGINT     REFERENCES users (id) ON DELETE CASCADE,
    event_type varchar(10),
    operation  varchar(10),
    entity_id  BIGINT
);
