CREATE TABLE users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     varchar,
    email    varchar,
    login    varchar,
    birthday date
);

ALTER TABLE users
    ADD CONSTRAINT email_unique_check UNIQUE (email);

CREATE TABLE friends
(
    user_id   INTEGER REFERENCES users (id),
    friend_id INTEGER REFERENCES users (id),
    status    BOOLEAN,
    CONSTRAINT friends_key PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE rating
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);

ALTER TABLE rating
    ADD COLUMN description varchar;

ALTER TABLE rating
    ADD CONSTRAINT name_unique_check UNIQUE (name);

CREATE TABLE film
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar,
    description varchar(100),
    realiseDate date,
    duration    INTEGER,
    rating_id   INTEGER REFERENCES rating (id)
);

CREATE TABLE likes
(
    film_id INTEGER REFERENCES film (id),
    user_id INTEGER REFERENCES users (id),
    CONSTRAINT likes_key PRIMARY KEY (film_id, user_id)

);

CREATE TABLE genre
(
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name VARCHAR
);

ALTER TABLE genre
    ADD CONSTRAINT genre_name_unique_check UNIQUE (name);

CREATE TABLE film_genre
(
    film_id INTEGER REFERENCES film(id),
    genre_id INTEGER REFERENCES genre (id),
    CONSTRAINT film_genre_key PRIMARY KEY (film_id, genre_id)
);
